#ifndef CLUELESS_WIN32_KEYCODES_H
#define CLUELESS_WIN32_KEYCODES_H

#include <windows.h>

#define ENGINE_KEYCODE WORD

#define ENGINE_KEYCODE_LBUTTON	VK_LBUTTON
#define ENGINE_KEYCODE_RBUTTON	VK_RBUTTON
#define ENGINE_KEYCODE_CANCEL	VK_CANCEL
#define ENGINE_KEYCODE_MBUTTON	VK_MBUTTON

#define ENGINE_KEYCODE_BACK	VK_BACK
#define ENGINE_KEYCODE_TAB	VK_TAB

#define ENGINE_KEYCODE_CLEAR	VK_CLEAR
#define ENGINE_KEYCODE_RETURN	VK_RETURN

#define ENGINE_KEYCODE_SHIFT	VK_SHIFT
#define ENGINE_KEYCODE_CONTROL	VK_CONTROL
#define ENGINE_KEYCODE_MENU		VK_MENU
#define ENGINE_KEYCODE_PAUSE	VK_PAUSE
#define ENGINE_KEYCODE_CAPITAL	VK_CAPITAL

#define ENGINE_KEYCODE_ESCAPE	VK_ESCAPE

#define ENGINE_KEYCODE_SPACE		VK_SPACE
#define ENGINE_KEYCODE_PAGE_UP		VK_PRIOR
#define ENGINE_KEYCODE_PAGE_DOWN	VK_NEXT
#define ENGINE_KEYCODE_END			VK_END
#define ENGINE_KEYCODE_HOME			VK_HOME
#define ENGINE_KEYCODE_LEFT			VK_LEFT
#define ENGINE_KEYCODE_UP			VK_UP
#define ENGINE_KEYCODE_RIGHT		VK_RIGHT
#define ENGINE_KEYCODE_DOWN			VK_DOWN
#define ENGINE_KEYCODE_SELECT		VK_SELECT
#define ENGINE_KEYCODE_PRINT		VK_PRINT
#define ENGINE_KEYCODE_EXECUTE		VK_EXECUTE
#define ENGINE_KEYCODE_PRINT_SCREEN	VK_SNAPSHOT
#define ENGINE_KEYCODE_INSERT		VK_INSERT
#define ENGINE_KEYCODE_DELETE		VK_DELETE
#define ENGINE_KEYCODE_HELP			VK_HELP

#define ENGINE_KEYCODE_0	VK_0
#define ENGINE_KEYCODE_1	VK_1
#define ENGINE_KEYCODE_2	VK_2
#define ENGINE_KEYCODE_3	VK_3
#define ENGINE_KEYCODE_4	VK_4
#define ENGINE_KEYCODE_5	VK_5
#define ENGINE_KEYCODE_6	VK_6
#define ENGINE_KEYCODE_7	VK_7
#define ENGINE_KEYCODE_8	VK_8
#define ENGINE_KEYCODE_9	VK_9

#define ENGINE_KEYCODE_A	VK_A
#define ENGINE_KEYCODE_B    VK_B
#define ENGINE_KEYCODE_C    VK_C
#define ENGINE_KEYCODE_D    VK_D
#define ENGINE_KEYCODE_E    VK_E
#define ENGINE_KEYCODE_F    VK_F
#define ENGINE_KEYCODE_G    VK_G
#define ENGINE_KEYCODE_H    VK_H
#define ENGINE_KEYCODE_I    VK_I
#define ENGINE_KEYCODE_J    VK_J
#define ENGINE_KEYCODE_K    VK_K
#define ENGINE_KEYCODE_L    VK_L
#define ENGINE_KEYCODE_M    VK_M
#define ENGINE_KEYCODE_N    VK_N
#define ENGINE_KEYCODE_O    VK_O
#define ENGINE_KEYCODE_P    VK_P
#define ENGINE_KEYCODE_Q    VK_Q
#define ENGINE_KEYCODE_R    VK_R
#define ENGINE_KEYCODE_S    VK_S
#define ENGINE_KEYCODE_T    VK_T
#define ENGINE_KEYCODE_U    VK_U
#define ENGINE_KEYCODE_V    VK_V
#define ENGINE_KEYCODE_W    VK_W
#define ENGINE_KEYCODE_X    VK_X
#define ENGINE_KEYCODE_Y    VK_Y
#define ENGINE_KEYCODE_Z    VK_Z

#define ENGINE_KEYCODE_LWIN	VK_LWIN
#define ENGINE_KEYCODE_RWIN	VK_RWIN
#define ENGINE_KEYCODE_APPS	VK_APPS

#define ENGINE_KEYCODE_SLEEP		VK_SLEEP
#define ENGINE_KEYCODE_NUMPAD0		VK_NUMPAD0
#define ENGINE_KEYCODE_NUMPAD1		VK_NUMPAD1
#define ENGINE_KEYCODE_NUMPAD2		VK_NUMPAD2
#define ENGINE_KEYCODE_NUMPAD3		VK_NUMPAD3
#define ENGINE_KEYCODE_NUMPAD4		VK_NUMPAD4
#define ENGINE_KEYCODE_NUMPAD5		VK_NUMPAD5
#define ENGINE_KEYCODE_NUMPAD6		VK_NUMPAD6
#define ENGINE_KEYCODE_NUMPAD7		VK_NUMPAD7
#define ENGINE_KEYCODE_NUMPAD8		VK_NUMPAD8
#define ENGINE_KEYCODE_NUMPAD9		VK_NUMPAD9
#define ENGINE_KEYCODE_MULTIPLY		VK_MULTIPLY
#define ENGINE_KEYCODE_ADD			VK_ADD
#define ENGINE_KEYCODE_SEPARATOR	VK_SEPARATOR
#define ENGINE_KEYCODE_SUBTRACT		VK_SUBTRACT
#define ENGINE_KEYCODE_DECIMAL		VK_DECIMAL
#define ENGINE_KEYCODE_DIVIDE		VK_DIVIDE
#define ENGINE_KEYCODE_F1			VK_F1
#define ENGINE_KEYCODE_F2			VK_F2
#define ENGINE_KEYCODE_F3			VK_F3
#define ENGINE_KEYCODE_F4			VK_F4
#define ENGINE_KEYCODE_F5			VK_F5
#define ENGINE_KEYCODE_F6			VK_F6
#define ENGINE_KEYCODE_F7			VK_F7
#define ENGINE_KEYCODE_F8			VK_F8
#define ENGINE_KEYCODE_F9			VK_F9
#define ENGINE_KEYCODE_F10			VK_F10
#define ENGINE_KEYCODE_F11			VK_F11
#define ENGINE_KEYCODE_F12			VK_F12
#define ENGINE_KEYCODE_F13			VK_F13
#define ENGINE_KEYCODE_F14			VK_F14
#define ENGINE_KEYCODE_F15			VK_F15
#define ENGINE_KEYCODE_F16			VK_F16
#define ENGINE_KEYCODE_F17			VK_F17
#define ENGINE_KEYCODE_F18			VK_F18
#define ENGINE_KEYCODE_F19			VK_F19
#define ENGINE_KEYCODE_F20			VK_F20
#define ENGINE_KEYCODE_F21			VK_F21
#define ENGINE_KEYCODE_F22			VK_F22
#define ENGINE_KEYCODE_F23			VK_F23
#define ENGINE_KEYCODE_F24			VK_F24

#define ENGINE_KEYCODE_NUMLOCK	VK_NUMLOCK
#define ENGINE_KEYCODE_SCROLL	VK_SCROLL

#define ENGINE_KEYCODE_LSHIFT	VK_LSHIFT
#define ENGINE_KEYCODE_RSHIFT	VK_RSHIFT
#define ENGINE_KEYCODE_LCONTROL	VK_LCONTROL
#define ENGINE_KEYCODE_RCONTROL	VK_RCONTROL
#define ENGINE_KEYCODE_LMENU	VK_LMENU
#define ENGINE_KEYCODE_RMENU	VK_RMENU

#endif